# Generated by Django 4.0.4 on 2022-04-13 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='has_sub',
            field=models.BooleanField(verbose_name='Имеет подколлекцию'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='link',
            field=models.CharField(max_length=200, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=200, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='site',
            field=models.CharField(max_length=200, verbose_name='Интернет сайт'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='phone',
            field=models.CharField(max_length=200, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='subcollection',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.collection', verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='subcollection',
            name='link',
            field=models.CharField(max_length=200, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='subcollection',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
    ]
